# Generated by Django 4.1.3 on 2022-11-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
